import json
from pathlib import Path
from uuid import UUID

import httpx
import pytest

from offence.bolt11 import decode_invoice
from offence.strike import Strike, strike_address, btc_msat

INVOICE = (Path(__file__).parent/'fixtures/bolt11-description-hash.txt').read_text().strip()
AMOUNT = {'currency':'BTC','amount':'0.02000000000'}
COMMITMENT = '3925b6f67e2c340036ed12093dd44e0368df1b6ea26c53dbe4811f58fd5db8c1'
RECEIVER = '00000000-0000-4000-8000-000000000001'
INVOICE_ID = '00000000-0000-4000-8000-000000000002'


def test_official_bolt11_vector_and_corruption():
    # Official BOLT11 description-hash example, not generated by this parser.
    # https://github.com/lightning/bolts/blob/master/11-payment-encoding.md
    result=decode_invoice(INVOICE)
    assert result['amount_msat']==2_000_000_000
    assert result['description_hash']==COMMITMENT
    assert result['expires']==1496314658+3600
    assert decode_invoice(INVOICE.upper())==result
    for bad in [INVOICE[:-1]+'q',INVOICE[:100],INVOICE.replace('lnbc','lnbcrt',1),INVOICE[:10].upper()+INVOICE[10:]]:
        with pytest.raises(ValueError): decode_invoice(bad)


@pytest.mark.parametrize('value',['a@evil.com','a@strike.me.evil','../a@strike.me','a@strike.me/x','https://strike.me/a','a b@strike.me'])
def test_address_rejects_non_strike_or_ambiguous_identifiers(value):
    with pytest.raises(ValueError): strike_address(value)


@pytest.mark.parametrize('value',['NaN','Infinity','-1','1e-9','0.000000000001',0.01])
def test_amounts_are_exact_and_bounded(value):
    with pytest.raises(ValueError): btc_msat(value)


async def test_strike_routes_to_named_receiver_and_requires_completed_credit(monkeypatch):
    monkeypatch.setattr('offence.strike.time.time',lambda:1496314658)
    invoice={};state={'value':'UNPAID','credit':False}
    seen=[]
    def handler(request):
        assert request.url.host=='api.strike.me'
        assert request.headers['authorization']=='Bearer test-only-key'
        seen.append((request.method,request.url.path))
        if request.url.path=='/v1/accounts/handle/alice/profile':
            return httpx.Response(200,json={'id':RECEIVER,'handle':'alice','canReceive':True,
                'currencies':[{'currency':'BTC','isAvailable':True,'isInvoiceable':True}]})
        if request.url.path=='/v1/invoices/handle/alice':
            body=json.loads(request.content);UUID(body['correlationId'])
            assert body['amount']==AMOUNT
            invoice.update(invoiceId=INVOICE_ID,receiverId=RECEIVER,correlationId=body['correlationId'],amount=AMOUNT,state='UNPAID')
            return httpx.Response(201,json=invoice)
        if request.url.path==f'/v1/invoices/{INVOICE_ID}/quote':
            assert json.loads(request.content)=={'descriptionHash':COMMITMENT}
            return httpx.Response(201,json={'lnInvoice':INVOICE,'sourceAmount':AMOUNT,'targetAmount':AMOUNT})
        assert request.method=='GET' and request.url.path==f'/v1/invoices/{INVOICE_ID}'
        return httpx.Response(200,json={**invoice,'state':state['value'],
            'transactions':[{'state':'COMPLETED' if state['credit'] else 'PENDING','amountReceived':AMOUNT}]})
    wallet=Strike('ALICE@strike.me','test-only-key',transport=httpx.MockTransport(handler))
    issued=await wallet.create_batch_invoice(2_000_000_000,COMMITMENT,60)
    assert issued['payment_hash']==decode_invoice(INVOICE)['payment_hash']
    assert not await wallet.settled_batch(issued['reference'],issued['payment_hash'],2_000_000_000)
    state['value']='PAID'
    assert not await wallet.settled_batch(issued['reference'],issued['payment_hash'],2_000_000_000)
    state['credit']=True
    assert await wallet.settled_batch(issued['reference'],issued['payment_hash'],2_000_000_000)
    invoice['receiverId']='00000000-0000-4000-8000-000000000003'
    with pytest.raises(ValueError,match='identity'):
        await wallet.settled_batch(issued['reference'],issued['payment_hash'],2_000_000_000)
    assert not any('payment' in path or 'payout' in path for _,path in seen)


async def test_strike_rejects_conversion_and_remote_errors(monkeypatch):
    wallet=Strike('alice@strike.me','test-key')
    async def profile(): return RECEIVER
    wallet.profile=profile
    async def call(method,path,data=None):
        if '/handle/' in path:
            return {'invoiceId':INVOICE_ID,'receiverId':RECEIVER,'correlationId':data['correlationId'],'amount':AMOUNT}
        return {'sourceAmount':AMOUNT,'targetAmount':{'currency':'USD','amount':'5.00'},'lnInvoice':INVOICE}
    wallet.call=call
    with pytest.raises(ValueError,match='currency'):
        await wallet.create_batch_invoice(2_000_000_000,COMMITMENT,60)
    for status in [302,401,429,500]:
        wallet=Strike('alice@strike.me','test-secret',transport=httpx.MockTransport(lambda r:httpx.Response(status,text='test-secret')))
        with pytest.raises(ValueError,match='Strike request failed') as exc:
            await wallet.check_network()
        assert 'test-secret' not in str(exc.value)
